#camera_name: "mindvision"
#exposure_ms: 2
#gamma: 0.5
#vid_pid: "f622:d13a"

# camera_name: "hikrobot"
# exposure_ms: 3
# gain: 10.0
# vid_pid: "2bdf:0001"
#并不是通过vid和pid来打开相机，而是通过重置USB设备时使用

camera_name: "daheng"
exposure_ms: 2
gamma: 2.85
vid_pid: "KE0200010097"
